
services:
  # Our PostgreSQL database
  db:
    image: postgres:latest
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!

  # Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8889:8080"
